name: peter-evans/create-pull-request (wrapped) v8
description: >-
  Composite wrapper for peter-evans/create-pull-request pinned to
  c0f553fe549906ede9cf27b5156039d195d2ece0
inputs:
  token:
    description: The token that the action will use to create and update the pull request.
    required: false
    default: ${{ github.token }}
  branch-token:
    description: >
      The token that the action will use to create and update the branch.
      Defaults to the value of `token`.
    required: false
  path:
    description: >
      Relative path under $GITHUB_WORKSPACE to the repository. Defaults to
      $GITHUB_WORKSPACE.
    required: false
  add-paths:
    description: >
      A comma or newline-separated list of file paths to commit. Paths should
      follow git's pathspec syntax. Defaults to adding all new and modified
      files.
    required: false
  commit-message:
    description: The message to use when committing changes.
    required: false
    default: '[create-pull-request] automated change'
  committer:
    description: >
      The committer name and email address in the format `Display Name
      <email@address.com>`. Defaults to the GitHub Actions bot user.
    required: false
    default: >-
      github-actions[bot]
      <41898282+github-actions[bot]@users.noreply.github.com>
  author:
    description: >
      The author name and email address in the format `Display Name
      <email@address.com>`. Defaults to the user who triggered the workflow run.
    required: false
    default: >-
      ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor
      }}@users.noreply.github.com>
  signoff:
    description: >-
      Add `Signed-off-by` line by the committer at the end of the commit log
      message.
    required: false
    default: false
  branch:
    description: The pull request branch name.
    required: false
    default: create-pull-request/patch
  delete-branch:
    description: >
      Delete the `branch` if it doesn't have an active pull request associated
      with it.
    required: false
    default: false
  branch-suffix:
    description: The branch suffix type when using the alternative branching strategy.
    required: false
  base:
    description: >
      The pull request base branch. Defaults to the branch checked out in the
      workflow.
    required: false
  push-to-fork:
    description: >
      A fork of the checked out parent repository to which the pull request
      branch will be pushed. e.g. `owner/repo-fork`. The pull request will be
      created to merge the fork's branch into the parent's base.
    required: false
  sign-commits:
    description: >-
      Sign commits as `github-actions[bot]` when using `GITHUB_TOKEN`, or your
      own bot when using GitHub App tokens.
    required: false
    default: false
  title:
    description: The title of the pull request.
    required: false
    default: Changes by create-pull-request action
  body:
    description: The body of the pull request.
    required: false
    default: >-
      Automated changes by
      [create-pull-request](https://github.com/peter-evans/create-pull-request)
      GitHub action
  body-path:
    description: >-
      The path to a file containing the pull request body. Takes precedence over
      `body`.
    required: false
  labels:
    description: A comma or newline separated list of labels.
    required: false
  assignees:
    description: A comma or newline separated list of assignees (GitHub usernames).
    required: false
  reviewers:
    description: >-
      A comma or newline separated list of reviewers (GitHub usernames) to
      request a review from.
    required: false
  team-reviewers:
    description: >
      A comma or newline separated list of GitHub teams to request a review
      from. Note that a `repo` scoped Personal Access Token (PAT) may be
      required.
    required: false
  milestone:
    description: The number of the milestone to associate the pull request with.
    required: false
  draft:
    description: >
      Create a draft pull request. Valid values are `true` (only on create),
      `always-true` (on create and update), and `false`.
    required: false
    default: false
  maintainer-can-modify:
    description: Indicates whether maintainers can modify the pull request.
    required: false
    default: true
outputs:
  pull-request-number:
    description: The pull request number
    value: ${{ steps.upstream.outputs.pull-request-number }}
  pull-request-url:
    description: The URL of the pull request.
    value: ${{ steps.upstream.outputs.pull-request-url }}
  pull-request-operation:
    description: >-
      The pull request operation performed by the action, `created`, `updated`
      or `closed`.
    value: ${{ steps.upstream.outputs.pull-request-operation }}
  pull-request-head-sha:
    description: The commit SHA of the pull request branch.
    value: ${{ steps.upstream.outputs.pull-request-head-sha }}
  pull-request-branch:
    description: The pull request branch name
    value: ${{ steps.upstream.outputs.pull-request-branch }}
  all_upstream_outputs:
    description: All outputs from upstream step as JSON
    value: ${{ toJSON(steps.upstream.outputs) }}
runs:
  using: composite
  steps:
    - id: upstream
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
      with:
        token: ${{ inputs.token }}
        branch-token: ${{ inputs.branch-token }}
        path: ${{ inputs.path }}
        add-paths: ${{ inputs.add-paths }}
        commit-message: ${{ inputs.commit-message }}
        committer: ${{ inputs.committer }}
        author: ${{ inputs.author }}
        signoff: ${{ inputs.signoff }}
        branch: ${{ inputs.branch }}
        delete-branch: ${{ inputs.delete-branch }}
        branch-suffix: ${{ inputs.branch-suffix }}
        base: ${{ inputs.base }}
        push-to-fork: ${{ inputs.push-to-fork }}
        sign-commits: ${{ inputs.sign-commits }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        body-path: ${{ inputs.body-path }}
        labels: ${{ inputs.labels }}
        assignees: ${{ inputs.assignees }}
        reviewers: ${{ inputs.reviewers }}
        team-reviewers: ${{ inputs.team-reviewers }}
        milestone: ${{ inputs.milestone }}
        draft: ${{ inputs.draft }}
        maintainer-can-modify: ${{ inputs.maintainer-can-modify }}
