name: azure/login (wrapped) v2
description: >-
  Composite wrapper for azure/login pinned to
  a457da9ea143d694b1b9c7c869ebb04ebe844ef5
inputs:
  creds:
    description: >-
      Paste output of `az ad sp create-for-rbac` as value of secret variable:
      AZURE_CREDENTIALS
    required: false
  client-id:
    description: ClientId of the Azure Service principal created.
    required: false
  tenant-id:
    description: TenantId of the Azure Service principal created.
    required: false
  subscription-id:
    description: Azure subscriptionId
    required: false
  enable-AzPSSession:
    description: >-
      Set this value to true to enable Azure PowerShell Login in addition to
      Azure CLI login
    required: false
    default: false
  environment:
    description: >-
      Name of the environment. Supported values are azurecloud, azurestack,
      azureusgovernment, azurechinacloud, azuregermancloud. Default being
      azurecloud
    required: false
    default: azurecloud
  allow-no-subscriptions:
    description: >-
      Set this value to true to enable support for accessing tenants without
      subscriptions
    required: false
    default: false
  audience:
    description: >-
      Provide audience field for access-token. Default value is
      api://AzureADTokenExchange
    required: false
    default: api://AzureADTokenExchange
  auth-type:
    description: >-
      The type of authentication. Supported values are SERVICE_PRINCIPAL,
      IDENTITY. Default value is SERVICE_PRINCIPAL
    required: false
    default: SERVICE_PRINCIPAL
outputs:
  all_upstream_outputs:
    description: All outputs from upstream step as JSON
    value: ${{ toJSON(steps.upstream.outputs) }}
runs:
  using: composite
  steps:
    - id: upstream
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
      with:
        creds: ${{ inputs.creds }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: ${{ inputs.enable-AzPSSession }}
        environment: ${{ inputs.environment }}
        allow-no-subscriptions: ${{ inputs.allow-no-subscriptions }}
        audience: ${{ inputs.audience }}
        auth-type: ${{ inputs.auth-type }}
