name: googleapis/release-please-action (wrapped) v5
description: >-
  Composite wrapper for googleapis/release-please-action pinned to
  45996ed1f6d02564a971a2fa1b5860e934307cf7
inputs:
  token:
    description: >-
      GitHub token for creating and grooming release PRs, defaults to using
      secrets.GITHUB_TOKEN
    required: false
    default: ${{ github.token }}
  release-type:
    description: >-
      what type of release is this, one of (ruby, python, node,
      terraform-module)
    required: false
    default: ''
  path:
    description: create a release from a path other than the repository's root
    required: false
    default: ''
  target-branch:
    description: branch to open pull release PR against (detected by default)
    required: false
    default: ''
  config-file:
    description: where can the config file be found in the project?
    required: false
    default: ''
  manifest-file:
    description: where can the manifest file be found in the project?
    required: false
    default: ''
  repo-url:
    description: configure github repository URL. Default `process.env.GITHUB_REPOSITORY`
    required: false
    default: ${{ github.repository }}
  github-api-url:
    description: configure github API URL. Default `https://api.github.com`
    required: false
    default: ${{ github.api_url }}
  github-graphql-url:
    description: configure github GraphQL URL. Default `https://api.github.com`
    required: false
    default: ${{ github.graphql_url }}
  fork:
    description: >-
      If true, send the PR from a fork. This requires the token to be a user
      that can create forks (e.g. not the default GITHUB_TOKEN)
    required: false
    default: false
  include-component-in-tag:
    description: >-
      If true, add prefix to tags and branches, allowing multiple libraries to
      be released from the same repository
    required: false
    default: false
  proxy-server:
    description: >-
      set proxy sever when you run this action behind a proxy. format is
      host:port e.g. proxy-host.com:8080
    required: false
    default: ''
  skip-github-release:
    description: if set to true, then do not try to tag releases
    required: false
    default: false
  skip-github-pull-request:
    description: if set to true, then do not try to open pull requests
    required: false
    default: false
  skip-labeling:
    description: if set to true, then do not try to label the PR
    required: false
    default: false
  changelog-host:
    description: The proto://host where commits live. Default `https://github.com`
    required: false
    default: ${{ github.server_url }}
  versioning-strategy:
    description: The versioning strategy to use.
    required: false
    default: default
  release-as:
    description: The version to release as.
    required: false
    default: ''
outputs:
  release_created:
    description: Whether a release was created
    value: ${{ steps.upstream.outputs.release_created }}
  tag_name:
    description: Tag name created
    value: ${{ steps.upstream.outputs.tag_name }}
  version:
    description: Release version
    value: ${{ steps.upstream.outputs.version }}
  major:
    description: Major version number
    value: ${{ steps.upstream.outputs.major }}
  minor:
    description: Minor version number
    value: ${{ steps.upstream.outputs.minor }}
  patch:
    description: Patch version or build metadata
    value: ${{ steps.upstream.outputs.patch }}
  pr:
    description: Release PR details as JSON
    value: ${{ steps.upstream.outputs.pr }}
  all_upstream_outputs:
    description: All outputs from upstream step as JSON
    value: ${{ toJSON(steps.upstream.outputs) }}
runs:
  using: composite
  steps:
    - id: upstream
      uses: >-
        googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7
      with:
        token: ${{ inputs.token }}
        release-type: ${{ inputs.release-type }}
        path: ${{ inputs.path }}
        target-branch: ${{ inputs.target-branch }}
        config-file: ${{ inputs.config-file }}
        manifest-file: ${{ inputs.manifest-file }}
        repo-url: ${{ inputs.repo-url }}
        github-api-url: ${{ inputs.github-api-url }}
        github-graphql-url: ${{ inputs.github-graphql-url }}
        fork: ${{ inputs.fork }}
        include-component-in-tag: ${{ inputs.include-component-in-tag }}
        proxy-server: ${{ inputs.proxy-server }}
        skip-github-release: ${{ inputs.skip-github-release }}
        skip-github-pull-request: ${{ inputs.skip-github-pull-request }}
        skip-labeling: ${{ inputs.skip-labeling }}
        changelog-host: ${{ inputs.changelog-host }}
        versioning-strategy: ${{ inputs.versioning-strategy }}
        release-as: ${{ inputs.release-as }}
