name: docker/login-action (wrapped) v3
description: >-
  Composite wrapper for docker/login-action pinned to
  c94ce9fb468520275223c153574b00df6fe4bcc9
inputs:
  registry:
    description: >-
      Server address of Docker registry. If not set then will default to Docker
      Hub
    required: false
  username:
    description: Username used to log against the Docker registry
    required: false
  password:
    description: Password or personal access token used to log against the Docker registry
    required: false
  ecr:
    description: Specifies whether the given registry is ECR (auto, true or false)
    required: false
  scope:
    description: Scope for the authentication token
    required: false
  logout:
    description: Log out from the Docker registry at the end of a job
    required: false
    default: 'true'
  registry-auth:
    description: Raw authentication to registries, defined as YAML objects
    required: false
outputs:
  all_upstream_outputs:
    description: All outputs from upstream step as JSON
    value: ${{ toJSON(steps.upstream.outputs) }}
runs:
  using: composite
  steps:
    - id: upstream
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        ecr: ${{ inputs.ecr }}
        scope: ${{ inputs.scope }}
        logout: ${{ inputs.logout }}
        registry-auth: ${{ inputs.registry-auth }}
